AffecterResult:
    path:     /AffecterResult
    defaults: { _controller: AnalysesBundle:Result:AffecterResult }
ResultaIndex:
    path:   /ResultaIndex/{id}
    defaults: { _controller: AnalysesBundle:Result:ResultaIndex }
    requirements:
        id:  \d+ 
imprimerResultaIndex:
    path:   /imprimerResultaIndex/{id}
    defaults: { _controller: AnalysesBundle:Result:imprimerResultaIndex }
    requirements:
        id:  \d+