utilisateur:
    resource: "@UtilisateurBundle/Resources/config/routing.yml"
    prefix:   /

analyses:
    resource: "@AnalysesBundle/Controller/"
    type:     annotation
    prefix:   /analyses

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"