utilisateur_homepage:
    path:     /
    defaults: { _controller: UtilisateurBundle:Default:index }
testMailer:
    path:     /testMailer
    defaults: { _controller: UtilisateurBundle:Default:testMailer }
    
logout_user:
    path:     /logoutUser
    defaults: { _controller: UtilisateurBundle:Default:logout }

    
Lims:
    resource: "@AnalysesBundle/Resources/config/lims/routing.yml"
    prefix:   /Lims