utilisateur_homepage:
    path:     /
    defaults: { _controller: UtilisateurBundle:Default:index }
testMailer:
    path:     /testMailer
    defaults: { _controller: UtilisateurBundle:Default:testMailer }
