LimsIndex:
    path:     /LimsIndex
    defaults: { _controller: AnalysesBundle:LimsA:index }
    
traitementDmD:
    path: /traitementDmD/{id}
    defaults: {_controller: AnalysesBundle:LimsA:traitementDmD}
    requirements:
        id:  \d+ 

        
AddEchantillonL:
    path: /AddNew/{id}
    defaults: {_controller: AnalysesBundle:LimsA:AddEchantillonL}
    requirements:
        id:  \d+
        
EchantillonItem:
    path: /EchantillonItem/{id}
    defaults: {_controller: AnalysesBundle:LimsA:EchantillonItem}
    requirements:
        id:  \d+
        
addEchantItem:
    path: /addEchantItem/{id}
    defaults: {_controller: AnalysesBundle:LimsA:addEchantItem}
    requirements:
        id:  \d+

addItem:
    path: /addItem/{id}
    defaults: {_controller: AnalysesBundle:LimsA:addItem}
    requirements:
        id:  \d+